### ISSUE TITLE
onprogress tests failing on chromedriver

### ISSUE THREAD

**Issue by dustinfarris** [pretenderjs/pretender#167]
2 failing tests on a fresh clone from master:

```
Chrome 52.0.2743 (Mac OS X 10.11.6) pretender invoking `onprogress` upload events don't keep firing once the request has ended FAILED
        No `onprogress` events are fired after the the request finalizes
        Expected: 4
        Actual: 3
            at /Users/dustin/Archive/pretender/node_modules/qunitjs/qunit/qunit.js:2194:12
            at /Users/dustin/Archive/pretender/test/calling_test.js:366:7

.....
Chrome 52.0.2743 (Mac OS X 10.11.6) pretender invoking `onprogress` download events don't keep firing once the request has ended FAILED
        No `onprogress` events are fired after the the request finalizes
        Expected: 4
        Actual: 3
            at /Users/dustin/Archive/pretender/node_modules/qunitjs/qunit/qunit.js:2194:12
            at /Users/dustin/Archive/pretender/test/calling_test.js:423:7
```

**Comment by stefanpenner** [comment]
Ya, these seems to be somewhat flakey.
